name: Web App CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install dependencies, build, and test
        run: |
          cd cinemagic-webapp
          npm install --legacy-peer-deps
          npm run build         

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: cinemagic-webapp/build


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}    
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_WEB }}
          package: ${{ github.workspace }}/cinemagic-webapp/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}         
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_WEB }}
          package: .