name: Web App CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./cinemagic-webapp

      - name: Build the React app
        run: npm run build
        working-directory: ./cinemagic-webapp
        env:
          CI: false
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}    
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_WEB }}
